function show_element(this, k, arg)

arguments
  this
  k double
  arg.update = true
end

% --- Insert element -------------------------------------------------------

% --- Description

this.Elm(k).cell.desc = text(this.axes, 0, 0, ...
  this.Elm(k).description, ...
  Margin = 1, ...
  Color = this.window.theme.color.figure.text, ...
  FontName = 'monospaced', ...
  FontSize = 10, ...
  Clipping = 'on');

% --- Control

switch this.Elm(k).type

  case 'edit'

    this.Elm(k).cell.bkg = rectangle(this.axes, ...
      FaceColor = this.window.theme.color.edit.background, ...
      EdgeColor = this.window.theme.color.figure.background, ...
      ButtonDownFcn = @this.click, ...
      UserData = k);

    this.Elm(k).cell.control = text(this.axes, 0, 0, ...
      num2str(this.Elm(k).default), ...
      Color = this.window.theme.color.figure.text, ...
      FontName = 'monospaced', ...
      FontSize = 10, ...
      HorizontalAlignment = 'center', ...
      Clipping = 'on', ...
      ButtonDownFcn = @this.click, ...
      UserData = k);

  case 'button'

    if this.Elm(k).value
      bColor = this.window.theme.color.button.on;
    else
      bColor = this.window.theme.color.button.off;
    end

    this.Elm(k).cell.bkg = rectangle(this.axes, ...
      FaceColor = bColor, ...
      EdgeColor = this.window.theme.color.figure.background, ...
      ButtonDownFcn = @this.click, ...
      UserData = k);
    
    this.Elm(k).cell.control = text(this.axes, 0, 0, ...
      this.Elm(k).string, ...
      Color = this.window.theme.color.figure.text, ...
      FontName = 'monospaced', ...
      FontSize = 10, ...
      HorizontalAlignment = 'center', ...
      Clipping = 'on', ...
      ButtonDownFcn = @this.click, ...
      UserData = k);

end

% --- Units

if sum(this.colSize)>1

  this.Elm(k).cell.units = text(this.axes, 0, 0, [' ' this.Elm(k).units], ...
    Color = this.window.theme.color.figure.text, ...
    FontName = 'monospaced', ...
    FontSize = 10, ...
    Clipping = 'on');

end

% Reset dynamic properties
if arg.update
  this.set_sizes;
end